# include_recipe 'deis::default'
# include_recipe 'deis::knife'
# include_recipe 'deis::postgresql'
# include_recipe 'deis::server'
# include_recipe 'deis::build'
# include_recipe 'deis::gitosis'
# include_recipe 'deis::logserver'

include_recipe 'deis::default'
include_recipe 'deis::etcd'
include_recipe 'deis::database'
include_recipe 'deis::cache'
include_recipe 'deis::server'
include_recipe 'deis::worker'
#include_recipe 'deis::builder'
#include_recipe 'deis::proxy'
